[package]
name = "move_dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
chrono = "0.4.31"
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8.8"
